<?php

/**
 * This custom module was started so I could adjust the 
 * weight of the shipping services that are currently
 * employeed by sightglass coffee.
 */


/**
 * Implements hook_commerce_shipping_service_info_alter().
 *
 * In addition to moving priority mail to the top of the stack
 * I have also altered the display title more clearly identify
 * this method as as USPS option.
 */
function sg_custom_commerce_shipping_service_info_alter(&$shipping_services) {
  if (isset($shipping_services['priority'])) {
    $shipping_services['priority']['weight'] = -10;
    $shipping_services['priority']['display_title'] = 'USPS Priority';
  }
}


/**
 * This function alters the normal user account form
 * by removing a bunch of Drupal defaults and reorganizing
 * the fields to more closely match the final design
 * 
 * @param  array $form       [description]
 * @param  array $form_state [description]
 * @param  string $form_id    [description]
 * 
 */
function sg_custom_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
    
  // Move current password down below email
  $form['account']['current_pass']['#weight'] = 1;
  $form['account']['current_pass']['#description'] = '';


  // Remove default Drupal field description
  $form['account']['mail']['#description'] = '';
  
  // Move password field and disable its description
  $form['account']['pass']['#weight'] = 2;
  $form['account']['pass']['#description'] = '';

  // Remove mimemail field from form
  $form['mimemail']['#type'] = 'value';
  $form['mimemail']['mimemail_textonly']['#type'] = 'value';

}