<?php

/**
 * This function describes the form that we're going
 * to be using for the upload process.
 * 
 * @param  [type] $form        [description]
 * @param  [type] $form_submit [description]
 * @return [type]              [description]
 */
function subscription_purchase_form($form, &$form_submit) {

  $form['username'] = array(
    '#username' => 'username',
    '#type' => 'textfield',
    '#title' => t('Enter username'),
    '#size' => 60,
  );

  $form['submit'] = array('#type' => 'submit', '#value' => t('Upload Lesson'));

  return $form;

}


/**
 * This is the validation routine for the content of 
 * the form. Right now I have just setup a really 
 * simple example throwing an error if the user submits
 * the form with no data
 * 
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
/*

Lets not do this, because we should use the braintree
form and js to handle the request, not Drupal.

function subscription_purchase_form_validate($form, &$form_state) {
  if (strlen($form_state['values']['username']) == 0) {
    form_set_error('username', 'what are you thinking, man!');
  }
}

*/
/**
 * This function just returns the form that we've created.
 * Basically, it's just a convenience function to keep our
 * code neat and readable
 * @return [type] [description]
 */

/*
Lets not do this, because we should use the braintree
form and js to handle the request, not Drupal.


function subscription_form() {
  return drupal_get_form('subscription_purchase_form');
}

*/


/**
 * This function registers custom block with drupal. In 
 * this function we can pass in parameters that define
 * the block, this mostly high level stuff and doesn't
 * have anything to do with the actual contents of the
 * blocks that we'll be using
 * 
 * @return [type] [description]
 */
function subscriptions_block_info() {
  $blocks = array();

  $blocks['braintree'] = array(
    'info' => t('Braintree'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * This functions allows us to inject the data that
 * we need into the block in question. This is kind of 
 * a list of the block we have on the system and where
 * there data is coming from. Their data is usually
 * coming from another function/method
 * 
 * @param  string $delta [description]
 * @return [type]        [description]
 */
function subscriptions_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'braintree':
      $block['subject'] = t('Brain Tree Starter');
      //$block['content'] = subscription_form(); this is old
      // we're going inject the braintree form here instead
      $block['content'] = '<h1>Braintree Credit Card Transaction Form</h1>
    <div>
      <form action="/create_transaction" method="POST" id="braintree-payment-form">
        <p>
          <label>Card Number</label>
          <input type="text" size="20" autocomplete="off" data-encrypted-name="number" />
        </p>
        <p>
          <label>CVV</label>
          <input type="text" size="4" autocomplete="off" data-encrypted-name="cvv" />
        </p>
        <p>
          <label>Expiration (MM/YYYY)</label>
          <input type="text" size="2" data-encrypted-name="month" /> / <input type="text" size="4" data-encrypted-name="year" />
        </p>
        <input type="submit" id="submit" />
      </form>
    </div>
    <script type="text/javascript" src="https://js.braintreegateway.com/v1/braintree.js"></script>
    <script type="text/javascript">
      var braintree = Braintree.create("MIIBCgKCAQEAs/hPHehk3Yq/utGpBsImUVXh0LDtFvM6/XJyNpMmjl3ZN9Hp/sftkI9gSIoS/zpIqSBQ+CK7SnyVjpmdq0wWshVZe2V+8dSySGnuj000rMIYTTUVwIecUAaIpNDE4CUh/3mSktUI2vAHcNzZ4RIQJFjaTFsOYQA0gp3WNilE28YahpnUVT1hkPZBvXkL2c4TF/dB6ucduv0627Hp42ks89IYWR2WvzxksjcME24fmo28UWviXraSR8MCGmCJ95VJ305oAXprgF7DPDQ/YBynAQ+K+GYQ2Rv1wrAaXyMILfpHL3SQ79IselfV43Zf9xuLN7/KmbnWFwi2XNi4/2KPvQIDAQAB");
      braintree.onSubmitEncryptForm("braintree-payment-form");
    </script>';
      break;
  }
  return $block;
}

